eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 2232
spring:
  application:
    name: trace-1
  zipkin:
    base-url: http://localhost:2235
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level: debug