eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 2226
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-b:
      path: /api-b/**
      serviceId: service-feign